# Generated by Django 2.1.7 on 2019-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
    ]
    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('is_primary', models.IntegerField(default=0)),
                ('is_indexed', models.IntegerField(default=0)),
                ('foreign_key_column_name', models.CharField(max_length=100, default=0)),
                ('foreign_key_table_name', models.CharField(max_length=100, default=0)),
            ],
        ),
    ]