# Generated by Django 2.1.7 on 2019-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=0)),
                ('is_indexed', models.BooleanField(default=0)),
                ('foreign_key_column_id', models.IntegerField(null=True)),
                ('foreign_key_table_id', models.IntegerField(null=True)),
            ],
        ),
    ]
