# Generated by Django 2.1.7 on 2019-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_1_id', models.IntegerField()),
                ('table_2_id', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
